Add devise
Surafels/Blog-app pull request #10
Opened 2024-01-16 13:37 UTC by Surafels

Hello 👋

In this branch, the following are implemented:

- Remove current_user method in ApplicationController
- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
- Can register a new user.
- User logs in with a combination of email and password.
- Hashed password should be stored in the database.
- Ask for confirmation of email.
- Can reset password.

2024-01-16 14:53 UTC, zeff96 requested changes
### Status: CHANGES REQUIRED ♻️
Hi @Surafels and @BHObserver , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/200w.webp?cid=ecf05e47wulwibee7u9kcue97y3k7lp0um8ill3b6g7zwuc1&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
:heavy_check_mark: Linters passing
:heavy_check_mark: Devise added


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-16 14:53 UTC, zeff96 commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
- [ ] Hey there! 🌟 According to the project requirements, it's important to include email confirmation during user registration. 😊 Unfortunately, in the existing setup, this feature is missing. To address this, please make sure to add the :confirmable module to Devise. 🔄 Additionally, in the Devise migration file, uncomment the confirmable column and then run the migration again. This step ensures that new users must confirm their email before being able to log in to the app. 📧👍

![Screenshot from 2024-01-16 17-39-19](https://github.com/Surafels/Blog-app/assets/112261237/a348af7e-8343-4a14-9fbf-b0c0f9dd3d7b)

```suggestion
  	devise :database_authenticatable, :registerable,
				:recoverable, :rememberable, :validatable, :confirmable
```

2024-01-16 14:53 UTC, zeff96 commented on app/views/devise/registrations/new.html.erb
> +<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
- [ ] Hey! 🌟 When trying to register on the app, an error occurs due to the name column in the user model being required (cannot be blank). To fix this, please ensure you've added a text_field for the name in the registration form. 📝

Also, there's an issue with the post_counter validation, as it's nil when registering a user. To address this, make sure to adjust the user migration and set a default value of zero for posts_counter. 🔄 These changes will guarantee a seamless user registration experience. 🚀

![Screenshot from 2024-01-16 17-38-43](https://github.com/Surafels/Blog-app/assets/112261237/1c33714e-2de8-49d1-878b-7cef3ea56609)

2024-01-16 20:02 UTC, DammyShittu requested changes
Hi @Surafels and @BHObserver,

## Highlights
✔️ Login and sign up features

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-16 20:02 UTC, DammyShittu commented on db/migrate/20240116192921_add_confirmed_at_to_users.rb
> +    add_column :users, :confirmed_at, :datetime
- [ ] You introduced this error after the last review. If you inspect your devise migration file you will see that you have `confirmed_at` already there. This migration is not needed. It is causing error during set up: `ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "confirmed_at" of relation "users" already exists`. Kindly remove it.

2024-01-16 20:02 UTC, DammyShittu commented on config/routes.rb
> +    root 'devise/sessions#new'
- **[OPTIONAL]** Consider not making this the root, instead make the users index page the root path. So that when the user logs in they are taken to the users list at once.

2024-01-18 14:11 UTC, Abenezer-Tilahun commented on db/migrate/20240116192921_add_confirmed_at_to_users.rb
> +    add_column :users, :confirmed_at, :datetime
Fixed.

2024-01-18 14:11 UTC, Abenezer-Tilahun commented on config/routes.rb
> +    root 'devise/sessions#new'
Fixed.

2024-01-18 14:15 UTC, Abenezer-Tilahun approved these changes
Hi @Surafels 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes. 
✔️ Good job for Implemented Blog app: add devise.


## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

2024-01-21 07:45 UTC, merged