Add validation and tests
Surafels/Blog-app pull request #3
Opened 2023-12-15 15:49 UTC by Surafels

Hello 👋 

In this branch, the following are implemented:

**The following validations are added:**

   - [ ] For the User model:

- Name must not be blank.
- PostsCounter must be an integer greater than or equal to zero.

   - [ ] For the Post model:

- Title must not be blank.
- Title must not exceed 250 characters.
- CommentsCounter must be an integer greater than or equal to zero.
- LikesCounter must be an integer greater than or equal to zero.

- [ ] Add unit specs for all models' methods and validations.

2023-12-15 17:14 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @Surafels , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- You have successfully added the validations and tested them. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-15 17:14 UTC, ridwanediallo commented on spec/models/user_spec.rb
> +end
- [ ] Great job adding the validations and testing them 👏. However, as stated in the requirement, all your models' methods should be tested too. So please, I would suggest you test the `recent_posts` method.

### Requirement :point_down: 
![Screenshot from 2023-12-15 16-53-41](https://github.com/Surafels/Blog-app/assets/89228743/2e79dda6-b073-458d-8fd9-45bc19a9024c)

2023-12-15 17:14 UTC, ridwanediallo commented on spec/models/post_spec.rb
> +end
- [ ] Great job adding the validations and testing them 👏. However, as stated in the requirement, all your models' methods should be tested too. So please, I would suggest you test the `update_user_posts_counter` and `recent_comments` methods.

### Requirement :point_down: 
![Screenshot from 2023-12-15 16-53-41](https://github.com/Surafels/Blog-app/assets/89228743/2e79dda6-b073-458d-8fd9-45bc19a9024c)

2023-12-15 17:14 UTC, ridwanediallo commented on spec/models/like_spec.rb
> +end
- [ ] Great job adding the validations and testing them 👏. However, as stated in the requirement, all your models' methods should be tested too. So please, I would suggest you test the `update_likes_counter` method.

### Requirement :point_down: 
![Screenshot from 2023-12-15 16-53-41](https://github.com/Surafels/Blog-app/assets/89228743/2e79dda6-b073-458d-8fd9-45bc19a9024c)

2023-12-15 17:14 UTC, ridwanediallo commented on spec/models/comment_spec.rb
> +end
- [ ] Great job adding the validations and testing them 👏. However, as stated in the requirement, all your models' methods should be tested too. So please, I would suggest you test the `update_post_comments_counter` method.

### Requirement :point_down: 
![Screenshot from 2023-12-15 16-53-41](https://github.com/Surafels/Blog-app/assets/89228743/2e79dda6-b073-458d-8fd9-45bc19a9024c)

2023-12-16 07:08 UTC, skyv26 approved these changes
## Hi @Surafels, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDJhMjgwMDkxOGE3NjA4MjIzYTVjYmExMTFiNmUxYjgxN2FlN2U5NCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PXM/FEzcI0TlDxkdbaHTwV/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implemented the test for the models methods ✅ 
![image](https://github.com/Surafels/Blog-app/assets/66476329/cac7be04-bb49-4ed9-8c93-05ee78b7f575)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-18 07:58 UTC, merged