integration specs for views and fix n+1 problems
Surafels/Blog-app pull request #8
Opened 2024-01-10 15:32 UTC by Surafels

Hello 👋

before 
![image](https://github.com/Surafels/Blog-app/assets/122282739/fe89bebf-8865-4611-8a8d-21310f855d2c)

after

![image](https://github.com/Surafels/Blog-app/assets/122282739/f53d031a-fd93-44d6-a930-6a70acfe41fc)

2024-01-11 09:01 UTC, OyePriscilla requested changes
Hi @Surafels 👍 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Write integration tests with Capybara gem. ✔️ 
Secure app from n+1 problems. ✔️ 

## Required Changes ♻️

- [ ] Please kindly fix the repo link that is broken in the setup section of your README file, I think there is a typo error in the URL. 🙏 

<img width="620" alt="codereview" src="https://github.com/Surafels/Blog-app/assets/103386183/248473e0-a592-4f06-a610-33f2b2724d8c">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-11 09:01 UTC, OyePriscilla commented on spec/features/post_index_spec.rb
> +  end
- [ ] Please kindly the add these missing tests that are highlighted below as stated in the requirements. 👍 

<img width="572" alt="codereview" src="https://github.com/Surafels/Blog-app/assets/103386183/1cddd467-2d57-407c-ab78-ef35dd10b976">

2024-01-12 20:46 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Surafels & @BHObserver, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- integration specs for views and fix n+1 problems ✔️
- Good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-12 20:52 UTC, merged

2024-01-16 08:36 UTC, prolajumokeoni reviewed
Hi @Surafels 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Integration specs for views completed ✅ 
   

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._